"""Sync agent outputs into dashboard/public/cases + index.json.
Run: python scripts/sync_dashboard_data.py
"""
import json
import shutil
from pathlib import Path

BASE = Path(__file__).parent.parent
DST = BASE / "dashboard" / "public" / "cases"
DST.mkdir(parents=True, exist_ok=True)

index = []
triggers = {}
with open(BASE / "data" / "case_pack.csv", newline="", encoding="utf-8") as f:
    import csv as _csv
    for r in _csv.DictReader(f):
        triggers[r["case_id"]] = r["trigger_type"]
for fp in sorted((BASE / "cases").glob("HHG-*.json")):
    if fp.suffixes[-2:] == [".llm", ".json"]:
        continue
    if fp.name.endswith(".brief.json"):
        continue
    d = json.loads(fp.read_text(encoding="utf-8"))
    cid = d["case_id"]
    shutil.copy(fp, DST / fp.name)
    llm_fp = BASE / "cases" / f"{cid}.llm.json"
    llm = json.loads(llm_fp.read_text(encoding="utf-8")) if llm_fp.exists() else None
    if llm:
        shutil.copy(llm_fp, DST / llm_fp.name)
    c, case = d["case"], llm["case"] if llm else {}
    trace_fp = BASE / "cases" / f"{cid}.trace.jsonl"
    has_trace = trace_fp.exists()
    if has_trace:
        shutil.copy(trace_fp, DST / trace_fp.name)
    index.append({
        "case_id": cid,
        "trigger": triggers.get(cid, ""),
        "has_trace": has_trace,
        "rule": {"verdict": c["verdict"], "p": c["fraud_probability"],
                 "pattern": c["pattern"], "exposure": c["exposure_usd"],
                 "sar": d["sar"]["file"]},
        "llm": ({"verdict": case["verdict"], "p": case["fraud_probability"],
                 "pattern": case["pattern"], "exposure": case["exposure_usd"],
                 "sar": llm["sar"]["file"]} if llm else None),
    })
(DST / "index.json").write_text(json.dumps(index, indent=1), encoding="utf-8")
print(f"synced {len(index)} cases -> {DST}")

# Bundled fallback so the UI renders even when static fetches fail:
# dashboard/src/lib/casefiles.js embeds every answer file (rule + LLM).
bundle = ["// GENERATED by scripts/sync_dashboard_data.py — do not edit by hand.",
          "export const CASE_FILES = {"]
for entry in index:
    cid = entry["case_id"]
    for suffix in ("", ".llm"):
        fp = BASE / "cases" / f"{cid}{suffix}.json"
        if fp.exists():
            bundle.append(f'  "{cid}{suffix}": {fp.read_text(encoding="utf-8")},')
bundle.append("};\nexport const CASE_INDEX = ")
bundle.append((DST / "index.json").read_text(encoding="utf-8"))
bundle.append(";")
(BASE / "dashboard" / "src" / "lib" / "casefiles.js").write_text(
    "\n".join(bundle), encoding="utf-8")
print("bundled case files for offline fallback")
